"""50 fixed seed prompts for the consistency experiment."""

SEED_PROMPTS = [
    "What is the capital of France?",
    "Explain the concept of entropy in thermodynamics.",
    "Write a haiku about the ocean.",
    "What is 17 multiplied by 23?",
    "Describe the water cycle in two sentences.",
    "What is the difference between a virus and a bacterium?",
    "Name three primary colors.",
    "Explain recursion to a 10-year-old.",
    "What is the Pythagorean theorem?",
    "Who wrote the play Hamlet?",
    "What is photosynthesis?",
    "Define machine learning in one sentence.",
    "What is the speed of light in a vacuum?",
    "List the first five prime numbers.",
    "What is the boiling point of water at sea level?",
    "Explain what DNA stands for.",
    "What year did World War II end?",
    "What is Newton's first law of motion?",
    "Describe the function of the mitochondria.",
    "What is the largest planet in our solar system?",
    "What is the chemical formula for water?",
    "Explain the concept of gravity briefly.",
    "What is the square root of 144?",
    "Who painted the Mona Lisa?",
    "What does CPU stand for?",
    "Explain what a black hole is.",
    "What is the Fibonacci sequence?",
    "What is the difference between weather and climate?",
    "Name the four fundamental forces of nature.",
    "What is Ohm's law?",
    "Explain what an algorithm is.",
    "What is the distance from Earth to the Moon approximately?",
    "Who discovered penicillin?",
    "What is the greenhouse effect?",
    "Explain what inflation means in economics.",
    "What is a neural network?",
    "What are the three states of matter?",
    "Who wrote 'A Brief History of Time'?",
    "What is the human genome?",
    "Explain what blockchain technology is.",
    "What is the theory of relativity?",
    "What is a prime number?",
    "Describe what an API is.",
    "What is the periodic table?",
    "Who invented the telephone?",
    "What is quantum mechanics?",
    "Explain what a derivative is in calculus.",
    "What is the Big Bang theory?",
    "What does RAM stand for in computing?",
    "Explain what open source software means.",
]

assert len(SEED_PROMPTS) == 50, f"Expected 50 prompts, got {len(SEED_PROMPTS)}"
